version: 2.1

jobs:
  build:
    docker:
      - image: rikhuijzer/hugo-latex-as-image:latest
    steps:
      - checkout
      - run:
          name: build-website
          command: nix-shell --run './myhugo.sh --source example-site && mv example-site/public .'
